theme: jekyll-theme-startbootstrap-agency
locale: "en-US"
name: nateandxtina.wedding
title: Christina & Nathan
title_separator: "-"
description: Check back for updates on our wedding!
url: https://nateandsxtina.wedding'
baseurl: ""
repository: nathang21/nateandxtina.wedding
markdown: kramdown

sass: # Enables the conversion of css/agency.min.scss to  css/agency.min.css
  style: compressed # Minify css/agency.min.css

